name: L1JetTag
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - root
  - pip
  - pip:
    - jupyter
    - h5py
    - python-time
    - argparse
    - tqdm
    - tensorflow==2.4.0
    - tensorflow_datasets
    - hls4ml[profiling]==0.6.0
    - git+https://github.com/jmduarte/hls4ml.git@split_pointwise_conv_by_rf_rebase#egg=hls4ml[profiling]
    - qkeras==0.9.0
    - scikit-learn
    - git+https://github.com/thesps/conifer.git
