name: L1JetTag
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - root
  - pip
  - pip:
    - jupyter
    - tensorflow==2.4.0
    - tensorflow_datasets
    - segmentation-models
    - keras==2.4.3
    - hls4ml[profiling]==0.6.0
    - scikit-learn
    - git+https://github.com/thesps/conifer.git
